### ISSUE TITLE
all Invoice method return only  ids of invoices

### ISSUE THREAD

**Issue by ashishinnotec** [revosystems/sage-one#1]
I want to fetching invoices details but i am getting only invoice id using this api call
 `$invoices = (new SalesInvoice($this->api))->where('show_payments_allocations', true)->all();`

I need to get all details of invoices.
Here is the which i am using it.

//Set the api params
 ```
$auth = new SageAuthFacade($data['client_id'], $data['client_secret']);
        $this->api = new SageFacade($auth, 'GB', $data['access_token']);
        $auth->setAuthKeys([
            'access_token'  => $data['access_token'],
            'refresh_token' => $data['refresh_token'],
        ], [
            'country'           => 'GB',
            'resource_owner_id' => $data['resource_owner_id'],
            'subscription_id'   => '',
        ]);
```

//Get all invoices call
`$invoices = (new SalesInvoice($this->api))->where('show_payments_allocations', true)->all();`

**Comment by PauBenetPrat** [comment]
Sorry, this is an unmaintained project and I can't remember how it worked...
I think we deprecated it. Maybe it's more useful for you this one:
https://github.com/revosystems/sage-accounting

**Comment by ashishinnotec** [comment]
> Sorry, this is an unmaintained project and I can't remember how it worked...
> I think we deprecated it. Maybe it's more useful for you this one:
> https://github.com/revosystems/sage-accounting

Okay
